### ISSUE TITLE
Define pom packaging

### ISSUE THREAD

**Issue by abelsromero** [mydoctor-maven-plugin/mydoctor-maven-plugin#28]
Seeing the output of `mvn help:describe -Dcmd=build` and `mvn help:describe -Dcmd=compile` for a asciidoc-lifecycle and a normal project I see these differences:

```
[INFO] 'build' is a phase within the 'asciidoctor-lifecycle-build' lifecycle, which has the following phases: 
```

```
It is a part of the lifecycle for the POM packaging 'jar'. This lifecycle includes the following phases:
```

Should the lifecycle define a default packaging? Honestly, don't know :O But it seems to me it should be done for correctness.

**Comment by rrialq** [comment]
Compare it with the output of `help:describe` for `site` phase, in the site lifecycle, it doesn't define a default packaging.
If you do `mvn help:describe -Dcmd=site` you'll get

`[INFO] 'site' is a phase within the 'site' lifecycle, which has the following phases:`

The output of describing the `build` phase is similar to the output describing the `site` phase.
This is the expected behaviour, because the functionality of both phases is very similar.

I think it is not necessery to define a default packaging for the new lifecycle, to allow the default lifecycle and the new lifecycle coexists in the same project.

**Comment by abelsromero** [comment]
Sounds reasonable to me.
